<a href="https://colab.research.google.com/github/Almclaren/undergrad-labs/blob/master/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [1]:
import torch

## zeros()

In [6]:
w=torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [7]:
w.size()

torch.Size([4, 3])

In [9]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [11]:
w = torch.randn(4,3)
w

tensor([[ 0.7120,  1.1385, -0.3511],
        [ 0.2251, -0.2040,  2.5005],
        [-0.7613,  2.5242, -1.6380],
        [-1.8932,  3.1071, -2.1772]])

In [12]:
t= torch.randn_like(w)
t

tensor([[-0.0744, -1.6885,  1.5991],
        [-0.0564, -0.1639,  1.1156],
        [-0.7755, -0.9890, -2.9206],
        [ 0.4296, -0.3861,  0.3436]])

## fill_()

In [13]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [14]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [17]:
type(w.numpy())

numpy.ndarray